In [2]:
import numpy as np
import pandas as pd 
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv('Downloads/EastWestAirlines.csv')
df.head()

ID#  Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  Bonus_miles  \
0    1    28143           0          1          1          1          174   
1    2    19244           0          1          1          1          215   
2    3    41354           0          1          1          1         4123   
3    4    14776           0          1          1          1          500   
4    5    97752           0          4          1          1        43300   

   Bonus_trans  Flight_miles_12mo  Flight_trans_12  Days_since_enroll  Award?  
0            1                  0                0               7000       0  
1            2                  0                0               6968       0  
2            4                  0                0               7034       0  
3            1                  0                0               6952       0  
4           26               2077                4               6935       1

In [5]:
from sklearn.preprocessing import StandardScaler

In [7]:
df.drop(['ID#','Award?','cc1_miles','cc2_miles','cc3_miles'],axis=1,inplace=True)

In [9]:
array=df.values
array

array([[28143,     0,   174, ...,     0,     0,  7000],
       [19244,     0,   215, ...,     0,     0,  6968],
       [41354,     0,  4123, ...,     0,     0,  7034],
       ...,
       [73597,     0, 25447, ...,     0,     0,  1402],
       [54899,     0,   500, ...,   500,     1,  1401],
       [ 3016,     0,     0, ...,     0,     0,  1398]], dtype=int64)

In [11]:
stscaler=StandardScaler().fit(array)
stscaler

StandardScaler()

In [12]:
x=stscaler.transform(array)

In [14]:
dbscan=DBSCAN(eps=.8,min_samples=7)
dbscan.fit(x)

DBSCAN(eps=0.8, min_samples=7)

In [15]:
dbscan.labels_

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [16]:
cl=pd.DataFrame(dbscan.labels_,columns=['clusters'])

In [17]:
df1=pd.concat([df,cl],axis=1)
df1

Balance  Qual_miles  Bonus_miles  Bonus_trans  Flight_miles_12mo  \
0       28143           0          174            1                  0   
1       19244           0          215            2                  0   
2       41354           0         4123            4                  0   
3       14776           0          500            1                  0   
4       97752           0        43300           26               2077   
...       ...         ...          ...          ...                ...   
3994    18476           0         8525            4                200   
3995    64385           0          981            5                  0   
3996    73597           0        25447            8                  0   
3997    54899           0          500            1                500   
3998     3016           0            0            0                  0   

      Flight_trans_12  Days_since_enroll  clusters  
0                   0               7000         0  
1                   0               6968         0  
2                   0               7034         0  
3                   0               6952         0  
4                   4               6935        -1  
...               ...                ...       ...  
3994                1               1403         0  
3995                0               1395         0  
3996                0               1402         0  
3997                1               1401         0  
3998                0               1398         0  

[3999 rows x 8 columns]

In [18]:
#Indexes of core data points
dbscan.core_sample_indices_

array([   0,    1,    2, ..., 3996, 3997, 3998], dtype=int64)

In [19]:
df1.groupby('clusters').count()

Balance  Qual_miles  Bonus_miles  Bonus_trans  Flight_miles_12mo  \
clusters                                                                     
-1            627         627          627          627                627   
 0           3367        3367         3367         3367               3367   
 1              5           5            5            5                  5   

          Flight_trans_12  Days_since_enroll  
clusters                                      
-1                    627                627  
 0                   3367               3367  
 1                      5                  5

In [20]:
df1.groupby('clusters').agg(['mean']).reset_index()

clusters        Balance  Qual_miles   Bonus_miles Bonus_trans  \
                     mean        mean          mean        mean   
0       -1  173658.661882  910.987241  38039.041467   20.985646   
1        0   54968.487080    1.522127  13269.207306    9.855361   
2        1   73766.400000    0.000000   6868.000000   11.000000   

  Flight_miles_12mo Flight_trans_12 Days_since_enroll  
               mean            mean              mean  
0       2148.948963         6.23126       4686.736842  
1        142.030294         0.45738       4012.202257  
2       2831.200000         9.20000       4490.000000

In [ ]:
# With the change in Epsilon value and sample size clusters very.
#With Epsilon value .8 and Sample 7 i am able to get 3 clusters.
# Number of data points in cluster three are very less.